### ISSUE TITLE
AttributeError: 'list' object has no attribute 'timeout_config'

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.linkchecker#120]
When trying to run this locally with a "new style config" like this:

```{
  "/customer/platform": {
    "email": ["them...@redacted.com", "others@redacted.com"],
    "base_uri": "https://www.hereorthere.ch",
    "timeout_config": "1",
    "upload_location": "/hereorthere/platform/intern/redaktion/edubs-moderatoren-innen/linkchecker/berichte"
  }
}```

I get the following:


```2020-07-06 15:51:59 WARNING Init Class Products.Archetypes.Schema.default has a security declaration for nonexistent method 'getRawExecCondition'
2020-07-06 15:52:01,217 - 4567 - INFO - Linkchecker instance started as expected.
Traceback (most recent call last):
  File "/Users/danieljowett/development/projects/edubsch.policy/parts/instance/bin/interpreter", line 434, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/danieljowett/development/projects/edubsch.policy/src/ftw.linkchecker/ftw/linkchecker/command/checking_links.py", line 55, in main
    check_links(app, args)
  File "/Users/danieljowett/development/projects/edubsch.policy/src/ftw.linkchecker/ftw/linkchecker/command/checking_links.py", line 40, in check_links
    accumulator.discover_broken_links()
  File "/Users/danieljowett/development/projects/edubsch.policy/src/ftw.linkchecker/ftw/linkchecker/link_accumulation.py", line 45, in discover_broken_links
    self._external_link_objs, self._site_config.configuration.timeout_config)
AttributeError: 'list' object has no attribute 'timeout_config'```

**Comment by busykoala** [comment]
@djowett-ftw, could you please provide the version of the ftw.linkchecker you were working with? On master, I believe it would raise an error trying to cast the alleged `list` into an `int` way before the point where it is failing in the traceback.
